
services:
  web:
    image: php7.4-apache
    container_name: php-apache
    ports:
      - "80:80"
    environment: 
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - COMPOSER_ALLOW_SUPERUSER=1
    volumes:
      - ./:/var/www/
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - db:db

  pma:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 1024M
    ports:
      - "8080:80"
    links:
      - db:db

  db:
    image: mariadb:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: changeme
      # MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      # MARIADB_RANDOM_ROOT_PASSWORD: "yes"

volumes:
  db-data:
